### ISSUE TITLE
How to run the project?

### ISSUE THREAD

**Issue by mostafaghadimi** [raphaelbrugier/spark-mongo-example#1]
Hi @raphaelbrugier,

I have installed Maven and Scala. I'm trying to run the project using `mvn scala:run` command, but I face with an error that is attached: 
[![enter image description here][1]][1]

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.360 s
[INFO] Finished at: 2019-08-19T19:19:12+04:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile (default) on project spark-mongo-example: Execution default of goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile failed.: CompileFailed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

Would you please tell me how can I resolve this problem? 

Thanks,
Mostafa

  [1]: https://i.stack.imgur.com/pvHQx.png

**Comment by raphaelbrugier** [comment]
Hi Mostafa,

Thanks for reporting the issue.
I have downloaded the project and tried, and I have the same issue.
I'm pretty sure this was working when I published the example.
It seems related to the scala maven plugin and the java version.
I wrote this post with java 8 and I now have java 10 installed, this seems to be the issue.

See this other github issue and proposed fix: https://github.com/davidB/scala-maven-plugin/issues/215#issuecomment-404284693

You can either downgrade your java version locally or try to upgrade the scala-maven plugin version (probably best, since I wrote that years ago)

**Comment by mostafaghadimi** [comment]
Hi @raphaelbrugier,

I have solved the issue and created a pull request.

Thanks for your attention,
Mostafa
